/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.10/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the java-library plugin for API and implementation separation.
    id("buildlogic.java-library-conventions")
    id("buildlogic.publish-conventions")
}

dependencies {
    implementation (libs.guava) // for hashing
    implementation(libs.dropwizard4.core)
    api(libs.micrometer.core)
    implementation(libs.bundles.logging)
    // SQL
    implementation(libs.jdbi.core)
    implementation(libs.jdbi.testing)
    implementation(libs.jdbi.sqlobject)

    implementation(libs.javax.inject)
    implementation(libs.dagger)
    annotationProcessor(libs.dagger.compiler)
    implementation(libs.immutables.annotations)
    annotationProcessor(libs.immutables.value)

    implementation(libs.codehead.metrics)
    implementation(libs.codehead.metrics.micrometer)

    implementation(libs.liquibase.core)


    testImplementation(libs.bundles.logback)
    testImplementation(libs.hsqldb)
    testImplementation(libs.c3p0)
    testImplementation(libs.bundles.testing)
    testImplementation(libs.codehead.test)
    testImplementation(libs.codehead.metrics.test)
    testAnnotationProcessor(libs.dagger.compiler)
    testAnnotationProcessor(libs.immutables.value)
}

